apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: peer-prep-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # Use the rewrite-target to manage the paths explicitly
    # nginx.ingress.kubernetes.io/websocket-services: "matching-service-service"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
    nginx.ingress.kubernetes.io/cors-allow-methods: 'PUT, GET, POST, OPTIONS, DELETE'
    nginx.ingress.kubernetes.io/cors-allow-headers: 'DNT,X-CustomHeader,X-LANG,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Key,X-Device-Id,Access-Control-Allow-Origin'
spec:
  rules:
    - host: peerprep.com
      http:
        paths:
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
          - path: /question-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: question-service-service
                port:
                  number: 5001
          - path: /user-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service-service
                port:
                  number: 5005
          - path: /matching-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: matching-service-service
                port:
                  number: 6006
