apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  AGORA_PRIMARY_CERTIFICATE: 88bc437cd09046e1a533ba16d631d794
  AGORA_ID: eb3028f5f8ee424e91bca93cf564dc39
  FRONTEND_SERVICE: https://peerprep.com
  QUESTION_PATH: /question-service
  USER_PATH: /user-service
  MATCHING_PATH: /matching-service/socket.io
  ROOM_PATH: https://peerprep.com/room-service
  VIDEO_PATH: /video-token-service
  CODE_EXECUTION_PATH: /code-execution-service
  QUESTION_SERVICE_PORT: "5001"
  USER_SERVICE_PORT: "5005"
  MATCHING_SERVICE_PORT: "6006"
  ROOM_SERVICE_PORT: "6007"
  VIDEO_TOKEN_SERVICE_PORT: "8080"
  NODE_ENV: "production"
  SIGNALING_PATH: wss://peerprep.com/video-token-service
